# Generated by Django 5.2.8 on 2025-12-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='archive_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Archiv-Nummer/Label'),
        ),
    ]
