# Generated by Django 5.2.8 on 2025-12-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0002_alter_piece_archive_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='master_pdfs/', verbose_name='Gesamt-PDF')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_pdfs', to='scorelib.piece')),
            ],
        ),
    ]
