# Generated by Django 5.2.8 on 2025-12-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0003_masterpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Untertitel'),
        ),
        migrations.DeleteModel(
            name='MasterPDF',
        ),
    ]
