# Generated by Django 5.2.8 on 2025-12-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0004_concert_subtitle_delete_masterpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Schwierigkeitsgrad'),
        ),
        migrations.AddField(
            model_name='piece',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dauer (mm:ss)'),
        ),
    ]
