# Generated by Django 5.2.8 on 2025-12-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0005_piece_difficulty_piece_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Dauer'),
        ),
    ]
