# Generated by Django 5.2.8 on 2025-12-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0006_alter_piece_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
