# Generated by Django 5.2.8 on 2025-12-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0007_alter_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
