# Generated by Django 5.2.8 on 2026-01-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0008_alter_concert_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Trompete', max_length=100, unique=True)),
                ('filter_strings', models.CharField(help_text='Komma-getrennte Liste (z.B. Trompete*, Flügelhorn*, Cornet*)', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='piece',
            name='archive_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Archiv-Label'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Schwierigkeit'),
        ),
        migrations.AddField(
            model_name='musicianprofile',
            name='instrument_groups',
            field=models.ManyToManyField(blank=True, to='scorelib.instrumentgroup'),
        ),
    ]
