# Generated by Django 5.2.8 on 2026-01-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0009_instrumentgroup_alter_piece_archive_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicianprofile',
            name='instrument_filter',
        ),
    ]
