# Generated by Django 5.2.8 on 2026-01-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0010_remove_musicianprofile_instrument_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianprofile',
            name='has_full_archive_access',
            field=models.BooleanField(default=False, verbose_name='Vollzugriff auf Archiv'),
        ),
    ]
