# Generated by Django 5.2.8 on 2026-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0011_musicianprofile_has_full_archive_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Hier kannst du Sätze (z.B. 1. Allegro) oder alternative Titel eintragen.', null=True, verbose_name='Zusatzinfos / Sätze / Alternativtitel'),
        ),
    ]
