# Generated by Django 5.2.8 on 2026-01-18 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0012_piece_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='is_owned_by_orchestra',
            field=models.BooleanField(default=True, help_text='Haken weg, wenn wir das Stück von jemand anderem geliehen haben.', verbose_name='Eigentum'),
        ),
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, verbose_name='Partner (Verein/Person/Verlag)')),
                ('loan_date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum (Erhalt/Gabe)')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Rückgabedatum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Bemerkungen')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_records', to='scorelib.piece')),
            ],
            options={
                'verbose_name': 'Verleih-/Leih-Historie',
                'ordering': ['-loan_date'],
            },
        ),
    ]
