# Generated by Django 5.2.8 on 2026-01-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0013_piece_is_owned_by_orchestra_loanrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='SKG Notenbank', max_length=200)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('legal_text', models.TextField(blank=True, help_text='HTML or plain-text legal / imprint content', null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='loanrecord',
            options={'ordering': ['-loan_date'], 'verbose_name': 'Loan History'},
        ),
    ]
