# Generated by Django 5.2.8 on 2026-01-30 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0014_sitesettings_alter_loanrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='z.B. Aufnahme bei YouTube', max_length=100, verbose_name='Beschreibung')),
                ('url', models.URLField(verbose_name='Link (URL)')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='scorelib.piece')),
            ],
            options={
                'verbose_name': 'Externer Link',
                'verbose_name_plural': 'Externe Links',
            },
        ),
    ]
