# Generated by Django 5.2.8 on 2026-02-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0015_externallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='audio_ripping_enabled',
            field=models.BooleanField(default=False, verbose_name='Audio-Ripping Feature aktivieren'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='band_name',
            field=models.CharField(default='Mein Orchester', max_length=200),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='title',
            field=models.CharField(help_text="z.B. 'Hörbeispiel' oder 'YouTube Video'", max_length=100, verbose_name='Beschreibung'),
        ),
    ]
