# Generated by Django 5.2.8 on 2026-02-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0016_sitesettings_audio_ripping_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='sort_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
